cameras:
- br: 0
  chunk_size: 30
  co: 1
  cx: 0.5
  cy: 0.5
  number: 1
  sl: 1
  url: ''
model_diagram: ''
project_name: test_proj
project_path: C:/Users/Jones-Lab/Documents/GitHub/CBAS/cbas_gui\test_proj
storage_path: C:/Users/Jones-Lab/Documents/GitHub/CBAS/cbas_gui\test_proj
